<?php
if ( ! defined( 'WPINC' ) ) {
    die;
}
?>
<div class="wf-tab-content" data-id="<?php echo $target_id;?>">

	<p><?php _e('The company and shipping from address details from the sections below will be used to fill up the invoice and related documents accordingly.','wf-woocommerce-packing-list'); ?></p>
	<h3 style="margin-bottom:0px; padding-bottom:5px; border-bottom:dashed 1px #ccc;"><?php _e('Company Info', 'wf-woocommerce-packing-list'); ?></h3>
	<table class="form-table wf-form-table">
	    <?php
		self::generate_form_field(array(
			array(
			'label'=>__("Name",'wf-woocommerce-packing-list'),
			'option_name'=>"woocommerce_wf_packinglist_companyname",
			),
			array(
				'type'=>"uploader",
				'label'=>__("Logo",'wf-woocommerce-packing-list'),
				'option_name'=>"woocommerce_wf_packinglist_logo",
			),
			array(
				'type'=>'textarea',
				'label'=>__("Footer",'wf-woocommerce-packing-list'),
				'option_name'=>"woocommerce_wf_packinglist_footer",
				'help_text'=>__("Set up a footer which will be used across the respective documents.",'wf-woocommerce-packing-list'),
			),
		));
		?>
	</table>

	<h3 style="margin-bottom:0px; padding-bottom:5px; border-bottom:dashed 1px #ccc;"><?php _e('Address(Sender details)', 'wf-woocommerce-packing-list'); ?></h3>
	<table class="form-table wf-form-table">
		<?php
		self::generate_form_field(array(
			array(
				'label'=>__("Department/Business Unit/Sender",'wf-woocommerce-packing-list'),
				'option_name'=>"woocommerce_wf_packinglist_sender_name",
			),
			array(
				'label'=>__("Address line 1",'wf-woocommerce-packing-list'),
				'option_name'=>"woocommerce_wf_packinglist_sender_address_line1",
			),
			array(
				'label'=>__("Address line 2",'wf-woocommerce-packing-list'),
				'option_name'=>"woocommerce_wf_packinglist_sender_address_line2",
			),
			array(
				'label'=>__("City",'wf-woocommerce-packing-list'),
				'option_name'=>"woocommerce_wf_packinglist_sender_city",
			)
		));
        $country_selected=Wf_Woocommerce_Packing_List::get_option('wf_country');
        if( strstr( $country_selected, ':' ))
        {
			$country_selected = explode( ':', $country_selected );
			$country         = current( $country_selected );
			$state           = end( $country_selected );                                            
		}else 
		{
			$country = $country_selected;
			$state   = '*';
		}                                 
        ?>
        <tr valign="top">
	        <th scope="row" >
	        	<label for="wf_country">
	        	<?php _e('Country/State','wf-woocommerce-packing-list'); ?></label></th>
	        <td>
	        	<select name="wf_country" data-placeholder="<?php esc_attr_e( 'Choose a country&hellip;', 'woocommerce' ); ?>">
						<?php WC()->countries->country_dropdown_options($country,$state ); ?>
         		</select>
	        </td>
	        <td></td>
	    </tr>
	    <?php
	    self::generate_form_field(array(
			array(
				'label'=>__("Postal code",'wf-woocommerce-packing-list'),
				'option_name'=>"woocommerce_wf_packinglist_sender_postalcode",
			),
			array(
				'label'=>__("Contact number",'wf-woocommerce-packing-list'), 
				'option_name'=>"woocommerce_wf_packinglist_sender_contact_number",
			),
			array(
				'label'=>__("VAT",'wf-woocommerce-packing-list'), 
				'option_name'=>"woocommerce_wf_packinglist_sender_vat",
			),
		));
	    ?>
	</table>
	<h3 style="margin-bottom:0px; padding-bottom:5px; border-bottom:dashed 1px #ccc;"><?php _e('Other settings', 'wf-woocommerce-packing-list'); ?></h3>
	<table class="form-table wf-form-table">
	    <?php
		self::generate_form_field(array(
			array(
				'type'=>"radio",
				'label'=>__("Preview before printing",'wf-woocommerce-packing-list'),
				'option_name'=>"woocommerce_wf_packinglist_preview",
				'radio_fields'=>array(
					'enabled'=>__('Enabled','wf-woocommerce-packing-list'),
					'disabled'=>__('Disabled','wf-woocommerce-packing-list')
				),
			),
			array(
				'type'=>"radio",
				'label'=>__("Enable RTL support",'wf-woocommerce-packing-list'),
				'option_name'=>"woocommerce_wf_add_rtl_support",
				'radio_fields'=>array(
					'Yes'=>__('Yes','wf-woocommerce-packing-list'),
					'No'=>__('No','wf-woocommerce-packing-list')
				),
				'help_text'=>__('RTL support in documents generated by browser','wf-woocommerce-packing-list'),
			)
		));
		?>
	</table>
	<?php 
    include "admin-settings-save-button.php";
    ?>
</div>